export enum filterKeys {
  ACCOUNT_ID = "account.id",
  ACCOUNT_BALANCE = "account.balance",
  ACCOUNT_PUBLICKEY = "account.publickey",
  BALANCE = "balance",
  CONTRACTID = "contractid",
  CONTRACT_ID = "contract.id",
  CREDIT_TYPE = "type",
  ENCODING = "encoding",
  FROM = "from",
  ENTITY_PUBLICKEY = "publickey",
  INDEX = "index",
  LIMIT = "limit",
  NONCE = "nonce",
  ORDER = "order",
  RESULT = "result",
  SCHEDULED = "scheduled",
  SCHEDULEID = "scheduleid",
  SCHEDULE_ID = "schedule.id",
  SERIAL_NUMBER = "serialnumber",
  SEQUENCE_NUMBER = "sequencenumber",
  TIMESTAMP = "timestamp",
  TOKENID = "tokenid",
  TOKEN_ID = "token.id",
  TOKEN_TYPE = "type",
  TOPIC_ID = "topic.id",
  TRANSACTION_TYPE = "transactiontype",
}